#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Trading_Sidekick.Resource", IsApplication=true)]

namespace Trading_Sidekick
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Trading_Sidekick.Data.Resource.String.ApplicationName = global::Trading_Sidekick.Resource.String.ApplicationName;
			global::Trading_Sidekick.Data.Resource.String.Hello = global::Trading_Sidekick.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int coppercoin = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int goldcoin = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hotBackground_small = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hotSplash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_list_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_search_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_visibility_black_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int silvercoin = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070010
			public const int itemList_listView = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int item_buysText = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int item_itemDesc = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int item_itemIcon = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int item_itemRarity = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int item_itemType = 2131165191;
			
			// aapt resource value: 0x7f07000f
			public const int item_listingList = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int item_radioBuys = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int item_radioSells = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int item_sellsText = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int item_watchCheck = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int listItem_icon = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int listItem_name = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int listingItem_listings = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int listingItem_price = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int listingItem_quantity = 2131165187;
			
			// aapt resource value: 0x7f070015
			public const int menu_search = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int menu_watchList = 2131165206;
			
			// aapt resource value: 0x7f070013
			public const int searchFrag_clearButton = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int searchFrag_searchButton = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int searchFrag_searchField = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int searchFrag_watchButton = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int toolbar = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomListListing = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ItemDisplay = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ItemList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SearchFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SplashLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int toolbar = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int top_menus = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int GW2HoTTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
