#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoneyManager.Android.Resource", IsApplication=true)]

namespace MoneyManager.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int bottom_toolbar = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int budget_end_picker = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int budget_start_picker = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int edit_budget_cancel = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int edit_budget_ok = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int edit_budget_spinner = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int edit_budget_title = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int edit_rbudget_period = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int edit_rbudget_spinner = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int edit_rbudget_title = 2131165194;
			
			// aapt resource value: 0x7f070013
			public const int edit_transaction_amount = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int edit_transaction_cancel = 2131165205;
			
			// aapt resource value: 0x7f070010
			public const int edit_transaction_date = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int edit_transaction_freq = 2131165199;
			
			// aapt resource value: 0x7f070016
			public const int edit_transaction_ok = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int edit_transaction_spinner = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int edit_transaction_subject = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int edit_transaction_title = 2131165198;
			
			// aapt resource value: 0x7f07001c
			public const int edit_wallet_cancel = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int edit_wallet_name = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int edit_wallet_ok = 2131165213;
			
			// aapt resource value: 0x7f070017
			public const int edit_wallet_title = 2131165207;
			
			// aapt resource value: 0x7f070021
			public const int filter_amounts_cancel = 2131165217;
			
			// aapt resource value: 0x7f07001e
			public const int filter_amounts_clear_button = 2131165214;
			
			// aapt resource value: 0x7f070020
			public const int filter_amounts_max = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int filter_amounts_min = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int filter_amounts_ok = 2131165218;
			
			// aapt resource value: 0x7f070026
			public const int filter_dates_cancel = 2131165222;
			
			// aapt resource value: 0x7f070023
			public const int filter_dates_clear_button = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int filter_dates_end_button = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int filter_dates_ok = 2131165223;
			
			// aapt resource value: 0x7f070024
			public const int filter_dates_start_button = 2131165220;
			
			// aapt resource value: 0x7f07002b
			public const int filter_listview_cancel = 2131165227;
			
			// aapt resource value: 0x7f070029
			public const int filter_listview_clear_button = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int filter_listview_listview = 2131165226;
			
			// aapt resource value: 0x7f07002c
			public const int filter_listview_ok = 2131165228;
			
			// aapt resource value: 0x7f070028
			public const int filter_listview_title = 2131165224;
			
			// aapt resource value: 0x7f07003e
			public const int filter_trans_amounts = 2131165246;
			
			// aapt resource value: 0x7f07003d
			public const int filter_trans_dates = 2131165245;
			
			// aapt resource value: 0x7f07003a
			public const int filter_trans_reset = 2131165242;
			
			// aapt resource value: 0x7f07003c
			public const int filter_trans_stores = 2131165244;
			
			// aapt resource value: 0x7f07003b
			public const int filter_trans_wallets = 2131165243;
			
			// aapt resource value: 0x7f07001b
			public const int linearLayout1 = 2131165211;
			
			// aapt resource value: 0x7f070002
			public const int list_view = 2131165186;
			
			// aapt resource value: 0x7f070031
			public const int login_button = 2131165233;
			
			// aapt resource value: 0x7f070030
			public const int login_pass_text = 2131165232;
			
			// aapt resource value: 0x7f07002e
			public const int login_user_text = 2131165230;
			
			// aapt resource value: 0x7f070001
			public const int main_content = 2131165185;
			
			// aapt resource value: 0x7f070036
			public const int main_logout_button = 2131165238;
			
			// aapt resource value: 0x7f070035
			public const int main_manage_acct_button = 2131165237;
			
			// aapt resource value: 0x7f070034
			public const int main_rectransactions_button = 2131165236;
			
			// aapt resource value: 0x7f070033
			public const int main_transactions_button = 2131165235;
			
			// aapt resource value: 0x7f070032
			public const int main_wallets_button = 2131165234;
			
			// aapt resource value: 0x7f070039
			public const int menu_add = 2131165241;
			
			// aapt resource value: 0x7f070038
			public const int menu_delete = 2131165240;
			
			// aapt resource value: 0x7f070037
			public const int menu_edit = 2131165239;
			
			// aapt resource value: 0x7f070040
			public const int menu_filters = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int menu_preferences = 2131165249;
			
			// aapt resource value: 0x7f07000b
			public const int rbudget_start_picker = 2131165195;
			
			// aapt resource value: 0x7f07003f
			public const int reset_db = 2131165247;
			
			// aapt resource value: 0x7f070018
			public const int tableLayout1 = 2131165208;
			
			// aapt resource value: 0x7f07002d
			public const int textView1 = 2131165229;
			
			// aapt resource value: 0x7f070019
			public const int textView11 = 2131165209;
			
			// aapt resource value: 0x7f07002f
			public const int textView2 = 2131165231;
			
			// aapt resource value: 0x7f070000
			public const int toolbar = 2131165184;
			
			// aapt resource value: 0x7f070011
			public const int transaction_subject_label = 2131165201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DataDisplay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditBudget = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditRecBudget = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditTransaction = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditWallet = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FiltersAmounts = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FiltersDates = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FiltersListView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Login = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int toolbar = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int data_bottom_menus = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int filter_transactions_popup = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int login_menus = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int top_menus = 2131099651;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
